#!/bin/bash

ulimit -n 10000
# --histogram=on \

sysbench --time=10 \
  --report-interval=1 \
  --mysql-debug=off \
  --threads=18 \
  --db-ps-mode=disable \
  --verbosity=3 \
  --mysql-host=127.0.0.1 \
  --mysql-port=33063 \
  --mysql-user=root \
  --percentile=75 \
  lua/sysbench/oltp_burn_cpus_high_priority.lua run
