#!/bin/bash

ulimit -n 10000
# --histogram=on \

sysbench --time=10 \
  --report-interval=1 \
  --mysql-debug=off \
  --threads=8 \
  --db-ps-mode=disable \
  --verbosity=3 \
  --mysql-host=127.0.0.1 \
  --mysql-port=33061 \
  --mysql-user=root \
  --percentile=95 \
  lua/sysbench/oltp_mixed_load.lua run
