#!/bin/bash

sysbench --time=10 \
  --mysql-debug=off \
  --histogram=on \
  --threads=32 \
  --mysql-host=127.0.0.1 \
  --mysql-port=33061 \
  --mysql-user=root \
  lua/sysbench/oltp_burn_cpus.lua run
